#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# This wizard provisions PRODUCTION. It must never touch the repository's own
# .env, which is the development environment and holds a different GitHub App,
# a different database, and a different encryption key.
ENV_FILE="${ENV_FILE:-$HOME/devme-production.env}"

# CI for this repo runs only `bun run check`, which needs no secrets
# (SKIP_ENV_VALIDATION=1). Nothing here calls set_secret, deliberately.

banner "devme: provision the production single VM"

# ── Stage 1: ground rules ─────────────────────────────────────────────────
stage "Where this writes, and what you need first"
say "This walks you through everything in .scratch/deploy-single-vm/spec.md"
say "that a person has to do in a browser: a domain, Cloudflare, a Hetzner"
say "box, a tunnel, a production GitHub App, and an R2 bucket."
say ""
warn "It writes to $ENV_FILE — NOT the repo's .env."
note "Your development .env keeps its own GitHub App, database and encryption"
note "key. Production must not share any of them."
say ""
say "Re-running is safe: every value already in that file is offered back as"
say "the default, and generated secrets are never regenerated."
say ""
for tool in openssl ssh scp; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "✓ $tool"
  else
    warn "missing: $tool — install it before continuing"
  fi
done
say ""
say "You will also need: a payment card (domain ~₹1,000/yr, Hetzner ~€3.79/mo),"
say "a Cloudflare account, and the GitHub account that owns this repository."
pause "Ready?"

# ── Stage 2: the domain ───────────────────────────────────────────────────
stage "Buy the domain"
say "GitHub needs one HTTPS origin that never changes — for the webhook and"
say "for the OAuth callback. That is what ends the tunnel-churn problem."
open_url "https://porkbun.com/products/domains"
step "Buy a domain at any registrar (Porkbun and Namecheap are both fine)."
step "Cheapest sensible TLDs: .com, .dev, .app. Avoid free/novelty TLDs —"
step "  some of them are blocked by corporate proxies and email providers."
say ""
note "Enter the hostname devme will be served at. Apex (devme.com) or a"
note "subdomain (app.devme.com) both work. No scheme, no trailing slash."
ask DEVME_DOMAIN "Domain:"
DEVME_DOMAIN="${DEVME_DOMAIN#https://}"
DEVME_DOMAIN="${DEVME_DOMAIN#http://}"
DEVME_DOMAIN="${DEVME_DOMAIN%/}"
write_env DEVME_DOMAIN "$DEVME_DOMAIN"
write_env NEXTAUTH_URL "https://${DEVME_DOMAIN}"
write_env NODE_ENV "production"
note "Origin will be: https://${DEVME_DOMAIN}"

# ── Stage 3: Cloudflare DNS ───────────────────────────────────────────────
stage "Point the domain at Cloudflare"
say "Cloudflare has to be authoritative for the domain before a tunnel can"
say "route a hostname to it."
open_url "https://dash.cloudflare.com/?to=/:account/add-site"
step "Add a site → enter ${DEVME_DOMAIN} → choose the Free plan."
step "Cloudflare shows two nameservers, e.g. 'xxx.ns.cloudflare.com'."
step "Copy both, go back to your registrar, and replace its nameservers with"
step "  them. (Registrars call this 'Custom DNS' or 'Nameservers'.)"
step "Return to Cloudflare and wait for the zone to read 'Active'. This is"
step "  usually minutes, occasionally hours."
say ""
step "On the Cloudflare dashboard, open the domain's Overview page. The"
step "  Account ID is in the right-hand column (or in the dashboard URL)."
ask CLOUDFLARE_ACCOUNT_ID "Paste the Cloudflare Account ID:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
say ""
if command -v dig >/dev/null 2>&1; then
  say "Checking who answers for ${DEVME_DOMAIN} right now:"
  dig +short NS "$DEVME_DOMAIN" | sed 's/^/    /' || true
  note "If those are not *.ns.cloudflare.com, the change has not propagated"
  note "yet. You can continue — nothing before stage 12 depends on it — but"
  note "the tunnel will not serve traffic until it has."
else
  note "dig not installed; verify in the Cloudflare dashboard that the zone"
  note "reads 'Active' before you finish."
fi
pause "Continue"

# ── Stage 4: the box ──────────────────────────────────────────────────────
stage "Create the Hetzner server"
say "One CAX11: 2 vCPU (ARM), 4 GB RAM, ~€3.79/month. Four gigabytes is the"
say "floor because the image is built on the box — next build beside a"
say "running Postgres will not fit in two."
say ""
if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
  note "Your public key (paste this into Hetzner):"
  printf '\n'; sed 's/^/    /' "$HOME/.ssh/id_ed25519.pub"; printf '\n'
elif confirm "No ~/.ssh/id_ed25519 found. Generate one now?"; then
  ssh-keygen -t ed25519 -N "" -f "$HOME/.ssh/id_ed25519"
  note "Your public key (paste this into Hetzner):"
  printf '\n'; sed 's/^/    /' "$HOME/.ssh/id_ed25519.pub"; printf '\n'
else
  warn "You will need to add some SSH key to the server yourself."
fi
open_url "https://console.hetzner.cloud/"
step "Create a project (or open your existing one) → Add Server."
step "Location: pick the one nearest your users. Nuremberg/Helsinki are the"
step "  cheapest; Singapore is closest to India if latency matters to you."
step "Image: Ubuntu 24.04."
step "Type: Arm64 (Ampere) → CAX11."
step "SSH keys: add the public key printed above. Do NOT enable password auth."
step "Create the server, then copy its public IPv4 address."
ask SERVER_IP "Paste the server's IPv4 address:"
write_env SERVER_IP "$SERVER_IP"
say ""
say "Testing SSH (accept the host key if prompted):"
if ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new "root@${SERVER_IP}" true 2>/dev/null; then
  note "✓ SSH works."
else
  warn "Could not SSH to root@${SERVER_IP} yet. The box may still be booting."
  note "Try 'ssh root@${SERVER_IP}' in another terminal before continuing."
  pause "Continue once SSH works"
fi

# ── Stage 5: prepare the box ──────────────────────────────────────────────
stage "Install Docker and close the firewall"
say "One remote command: Docker Engine with the Compose plugin, a firewall"
say "that allows nothing but SSH, and /opt/devme for the checkout."
say ""
note "Nothing but SSH is opened because ingress arrives through the tunnel as"
note "an outbound connection — the box never listens on 80 or 443."
say ""
if confirm "Run the bootstrap on ${SERVER_IP} now?"; then
  ssh -o StrictHostKeyChecking=accept-new "root@${SERVER_IP}" 'bash -s' <<'BOOTSTRAP'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl git ufw
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker
ufw allow OpenSSH
ufw --force enable
mkdir -p /opt/devme
echo "--- bootstrap complete ---"
docker --version
docker compose version
BOOTSTRAP
  note "✓ Box prepared."
else
  SKIPPED+=("bootstrap ${SERVER_IP}: install docker, ufw allow OpenSSH, mkdir /opt/devme")
  warn "Skipped. Do it by hand before deploying."
fi
pause "Continue"

# ── Stage 6: the tunnel ───────────────────────────────────────────────────
stage "Create the Cloudflare Tunnel"
say "cloudflared runs as one of the compose services and dials out to"
say "Cloudflare. That is what gives you TLS without certbot, and what makes"
say "the box's IP irrelevant — rebuild it and nothing GitHub knows changes."
open_url "https://one.dash.cloudflare.com/"
step "Zero Trust → Networks → Tunnels → Create a tunnel."
step "Connector type: Cloudflared. Name it 'devme-prod'."
step "On the install page, IGNORE the install instructions — compose runs the"
step "  connector for you. You only need the token: it is the long string in"
step "  the shown command, right after '--token'."
say ""
step "Then open the 'Public Hostname' tab and add a route:"
step "  Subdomain: (blank for apex, or the subdomain you chose)"
step "  Domain:    ${DEVME_DOMAIN}"
step "  Type:      HTTP"
step "  URL:       web:3000"
note "'web' is the compose service name — the connector resolves it on the"
note "compose network, which is why no port is published to the host."
ask_secret TUNNEL_TOKEN "Paste the tunnel token:"
write_env TUNNEL_TOKEN "$TUNNEL_TOKEN"

# ── Stage 7: generate the secrets ─────────────────────────────────────────
stage "Generate the production secrets"
say "These are generated here, not chosen. Re-running this wizard reuses"
say "whatever is already in $ENV_FILE rather than minting new values."
say ""

NEXTAUTH_SECRET=$(_existing NEXTAUTH_SECRET || true)
if [[ -z "$NEXTAUTH_SECRET" ]]; then
  NEXTAUTH_SECRET=$(openssl rand -base64 32)
  write_env NEXTAUTH_SECRET "$NEXTAUTH_SECRET"
else
  note "NEXTAUTH_SECRET already set — keeping it."
fi

ENCRYPTION_MASTER_KEY=$(_existing ENCRYPTION_MASTER_KEY || true)
FRESH_MASTER_KEY=0
if [[ -z "$ENCRYPTION_MASTER_KEY" ]]; then
  ENCRYPTION_MASTER_KEY=$(openssl rand -base64 32)
  write_env ENCRYPTION_MASTER_KEY "$ENCRYPTION_MASTER_KEY"
  FRESH_MASTER_KEY=1
else
  note "ENCRYPTION_MASTER_KEY already set — keeping it."
  note "Never regenerate this: every stored Provider Key is encrypted under it"
  note "and a new one makes all of them permanently unreadable."
fi

POSTGRES_PASSWORD=$(_existing POSTGRES_PASSWORD || true)
if [[ -z "$POSTGRES_PASSWORD" ]]; then
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
fi

GITHUB_WEBHOOK_SECRET=$(_existing GITHUB_WEBHOOK_SECRET || true)
if [[ -z "$GITHUB_WEBHOOK_SECRET" ]]; then
  GITHUB_WEBHOOK_SECRET=$(openssl rand -hex 32)
  write_env GITHUB_WEBHOOK_SECRET "$GITHUB_WEBHOOK_SECRET"
fi

write_env DATABASE_URL "postgresql://devme:${POSTGRES_PASSWORD}@postgres:5432/devme"
write_env REDIS_URL "redis://redis:6379"
note "Both point at compose service names, not localhost."
say ""
warn "Copy ENCRYPTION_MASTER_KEY somewhere that is not this laptop and not the"
warn "server — a password manager, or paper. A database backup without it"
warn "restores Provider Key ciphertext that nothing can ever decrypt."
say ""
if [[ "$FRESH_MASTER_KEY" == "1" ]]; then
  note "ENCRYPTION_MASTER_KEY = $ENCRYPTION_MASTER_KEY"
else
  note "(It is in $ENV_FILE if you still need to copy it.)"
fi
say ""
note "You will paste this webhook secret into GitHub in the next stage:"
note "GITHUB_WEBHOOK_SECRET = $GITHUB_WEBHOOK_SECRET"
pause "Stored the master key somewhere safe? Continue"

# ── Stage 8: create the production GitHub App ─────────────────────────────
stage "Create the production GitHub App"
say "A NEW App, under the account that owns this repository. The existing"
say "devme-review-dev App is untouched and stays pointed at your tunnel."
say ""
warn "Do NOT create a separate OAuth App for sign-in."
note "The dashboard calls GET /user/installations, which GitHub only answers"
note "for a user token minted by a GitHub App. A classic OAuth App's token"
note "silently returns nothing useful. This App supplies both identities."
say ""
open_url "https://github.com/settings/apps/new"
step "GitHub App name: must be globally unique, e.g. 'devme-review'."
step "Homepage URL: https://${DEVME_DOMAIN}"
say ""
say "Identifying and authorizing users:"
step "Callback URL: https://${DEVME_DOMAIN}/api/auth/callback/github"
step "Tick 'Request user authorization (OAuth) during installation' — it"
step "  sends a new user straight to sign-in after they install."
say ""
say "Webhook:"
step "Tick 'Active'."
step "Webhook URL: https://${DEVME_DOMAIN}/api/webhooks/github"
step "Webhook secret: paste exactly this —"
note "  $GITHUB_WEBHOOK_SECRET"
say ""
say "Repository permissions:"
step "  Contents ......... Read-only        (loads files for the index)"
step "  Issues ........... Read and write   (reads the spec, posts the comment)"
step "  Pull requests .... Read and write   (reads the diff)"
step "  Checks ........... Read and write   (posts the neutral Check Run)"
step "  Metadata ......... Read-only        (mandatory, auto-selected)"
say ""
say "Account permissions:"
step "  Email addresses .. Read-only"
note "Without this, anyone whose GitHub email is private cannot sign in."
say ""
say "Subscribe to events — exactly these:"
step "  Pull request"
step "  Installation"
step "  Installation repositories"
say ""
say "Where can this GitHub App be installed?"
step "  Choose 'Any account'."
note "'Only on this account' would stop the people you invite from installing"
note "it on their own repositories. The App stays unlisted either way — it is"
note "only reachable by people you give the install URL to."
say ""
step "Click 'Create GitHub App'."
pause "Created? Continue to capture its credentials"

# ── Stage 9: capture the App's credentials ────────────────────────────────
stage "Capture the App's credentials"
say "All four values are on the App's settings page you are now looking at."
open_url "https://github.com/settings/apps"
say ""
step "The URL ends /settings/apps/<slug>. Copy that slug."
ask GITHUB_APP_SLUG "App slug:"
write_env GITHUB_APP_SLUG "$GITHUB_APP_SLUG"
step "Near the top of the page: 'App ID'."
ask GITHUB_APP_ID "App ID:"
write_env GITHUB_APP_ID "$GITHUB_APP_ID"
step "Just below it: 'Client ID' (starts Iv...)."
ask GITHUB_OAUTH_CLIENT_ID "Client ID:"
write_env GITHUB_OAUTH_CLIENT_ID "$GITHUB_OAUTH_CLIENT_ID"
step "Click 'Generate a new client secret' and copy it — shown once."
ask_secret GITHUB_OAUTH_CLIENT_SECRET "Client secret:"
write_env GITHUB_OAUTH_CLIENT_SECRET "$GITHUB_OAUTH_CLIENT_SECRET"
say ""
step "Scroll to 'Private keys' → 'Generate a private key'. A .pem downloads."
ask PEM_PATH "Full path to the downloaded .pem:"
PEM_PATH="${PEM_PATH/#\~/$HOME}"
if [[ -f "$PEM_PATH" ]]; then
  GITHUB_APP_PRIVATE_KEY=$(awk 'BEGIN{ORS="\\n"} {print}' "$PEM_PATH")
  write_env GITHUB_APP_PRIVATE_KEY "\"$GITHUB_APP_PRIVATE_KEY\""
  note "Converted to the single-line \\n-escaped form appClient.ts expects."
  warn "Back this .pem up off-box, then delete it from your Downloads folder —"
  warn "it is a live credential and it cannot be re-downloaded, only replaced."
else
  warn "No file at '$PEM_PATH'."
  note "Convert it yourself later with:"
  note "  awk 'BEGIN{ORS=\"\\\\n\"} {print}' your-key.pem"
  note "and set GITHUB_APP_PRIVATE_KEY in $ENV_FILE to the output, quoted."
  SKIPPED+=("GITHUB_APP_PRIVATE_KEY: convert the .pem by hand into $ENV_FILE")
fi

# ── Stage 10: platform API keys ───────────────────────────────────────────
stage "Platform API keys (indexing)"
say "Indexing runs on OUR credentials, not the customer's Provider Key — Groq"
say "for summarisation, HuggingFace for embeddings. These are the same keys"
say "your development .env already uses; nothing here is per-customer."
say ""
if [[ -f .env ]] && confirm "Copy GROQ_API_KEY, GROQ_CHAT_MODEL and HF_TOKEN from ./.env?"; then
  for key in GROQ_API_KEY GROQ_CHAT_MODEL HF_TOKEN; do
    line=$(grep -E "^${key}=" .env | tail -n1 || true)
    value="${line#*=}"
    value="${value%\"}"; value="${value#\"}"
    if [[ -n "$value" ]]; then
      write_env "$key" "$value"
    else
      note "$key not found in ./.env — asking instead."
      ask "$key" "$key:"
      if [[ -n "${!key}" ]]; then write_env "$key" "${!key}"; fi
    fi
  done
else
  open_url "https://console.groq.com/keys"
  step "Create or copy a Groq API key."
  ask_secret GROQ_API_KEY "Groq API key:"
  write_env GROQ_API_KEY "$GROQ_API_KEY"
  open_url "https://huggingface.co/settings/tokens"
  step "Create a read token."
  ask_secret HF_TOKEN "HuggingFace token:"
  write_env HF_TOKEN "$HF_TOKEN"
  ask GROQ_CHAT_MODEL "Groq chat model (blank to use the app default):"
  if [[ -n "$GROQ_CHAT_MODEL" ]]; then write_env GROQ_CHAT_MODEL "$GROQ_CHAT_MODEL"; fi
fi
say ""
warn "Groq retires hosted models without notice. A stale model 404s on every"
warn "call, and indexing swallows per-file failures — so the only symptom is"
warn "an index that silently never fills. Check the model is still listed:"
note "  https://console.groq.com/docs/models"

# ── Stage 11: backups ─────────────────────────────────────────────────────
stage "Create the R2 bucket for backups"
say "A nightly pg_dump goes here. R2 because you are already on Cloudflare,"
say "the free tier is far larger than this database, and egress costs nothing"
say "— which matters only on the day you need it, which is the day to have no"
say "obstacles."
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "R2 → Create bucket. Name it 'devme-backups'. Location: nearest you."
ask R2_BUCKET "Bucket name:"
write_env R2_BUCKET "$R2_BUCKET"
say ""
step "R2 → API → 'Manage API tokens' → 'Create API token'."
step "Permission: 'Object Read & Write'."
step "Scope it to the ${R2_BUCKET} bucket only, not all buckets."
step "Create it, then copy BOTH values shown — they are shown once."
ask R2_ACCESS_KEY_ID "Access Key ID:"
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
ask_secret R2_SECRET_ACCESS_KEY "Secret Access Key:"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
write_env R2_ENDPOINT "https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com"
note "Endpoint derived from your account ID: "
note "  https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com"

# ── Stage 12: ship it ─────────────────────────────────────────────────────
stage "Send the environment to the box"
chmod 600 "$ENV_FILE"
say "Everything is captured. The last step is putting $ENV_FILE on the server"
say "at /opt/devme/.env, readable only by root."
say ""
note "It is not in the repository and never will be: compose reads it from"
note "disk, and it is not baked into the image."
say ""
if confirm "Copy $ENV_FILE to root@${SERVER_IP}:/opt/devme/.env now?"; then
  scp -o StrictHostKeyChecking=accept-new "$ENV_FILE" "root@${SERVER_IP}:/opt/devme/.env"
  ssh "root@${SERVER_IP}" "chmod 600 /opt/devme/.env"
  note "✓ Copied and locked down."
else
  SKIPPED+=("scp $ENV_FILE root@${SERVER_IP}:/opt/devme/.env && chmod 600")
fi

finish

say "What is left, in order:"
say ""
step "1. Clone the repo onto the box:"
note "     ssh root@${SERVER_IP} 'git clone <repo-url> /opt/devme/app'"
step "2. Deploy: ./deploy.sh  (builds the image on the box and starts compose)"
step "3. Run the migrations — 'prisma migrate deploy', NEVER 'migrate dev'."
warn "   This is the first time the migration chain has run against an empty"
warn "   database. Afterwards, confirm the index actually exists:"
note "     SELECT indexname FROM pg_indexes"
note "     WHERE indexname = 'SourceCodeEmbedding_summaryEmbedding_hnsw_idx';"
note "   A missing HNSW index does not error — it silently turns every"
note "   Codebase Index search into a sequential scan."
step "4. Visit https://${DEVME_DOMAIN} and sign in with GitHub."
step "5. Install the App on a repository:"
note "     https://github.com/apps/${GITHUB_APP_SLUG:-<slug>}/installations/new"
step "6. Paste an Anthropic key into /dashboard for that Installation."
step "7. Open a pull request whose body says 'Closes #<issue>' and watch."
step "8. Set up the nightly pg_dump to ${R2_BUCKET:-R2}, then RESTORE one by"
step "   hand into a scratch database before you invite anyone."
say ""
note "Gate conditions for this milestone: .scratch/deploy-single-vm/spec.md"
