#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "devme: GitHub OAuth App + GitHub App setup"

# ── Stage 1: tunnel ─────────────────────────────────────────────────────
stage "Start a tunnel to localhost:3000"
say "GitHub needs a public HTTPS URL to reach your webhook and OAuth callback."
say "This wizard uses cloudflared's free, account-less quick tunnel."
if ! command -v cloudflared >/dev/null 2>&1; then
  step "Installing cloudflared (it's in the Arch 'extra' repo)."
  if confirm "Run 'sudo pacman -S --noconfirm cloudflared' now?"; then
    sudo pacman -S --noconfirm cloudflared
  else
    warn "Install it yourself, then re-run this wizard: sudo pacman -S cloudflared"
    exit 1
  fi
else
  note "cloudflared already installed."
fi
say ""
say "Open a SEPARATE terminal (keep it running for the rest of this wizard,"
say "and for as long as you want the webhook / OAuth callback to work) and run:"
say ""
printf '    %scloudflared tunnel --url http://localhost:3000%s\n' "$BOLD" "$RESET"
say ""
say "It prints a line like:"
note "  https://random-words-1234.trycloudflare.com"
step "Copy that https://*.trycloudflare.com URL (no trailing slash)."
ask TUNNEL_URL "Paste the tunnel URL:"
TUNNEL_URL="${TUNNEL_URL%/}"
note "Using tunnel: $TUNNEL_URL"
note "Remember: this URL changes every time you restart cloudflared. If it"
note "changes later, update the OAuth App callback and the GitHub App's"
note "webhook + callback URLs to match, or just re-run this wizard."

# ── Stage 2: GitHub OAuth App (dashboard sign-in only) ────────────────────
stage "GitHub OAuth App (dashboard sign-in)"
say "This is separate from the GitHub App in the next stage. It only lets"
say "someone sign in to the devme dashboard — it grants no repository access"
say "(see docs/adr/0001)."
open_url "https://github.com/settings/applications/new"
step "Application name: anything, e.g. 'devme (dev)'."
step "Homepage URL: ${TUNNEL_URL}"
step "Authorization callback URL: ${TUNNEL_URL}/api/auth/callback/github"
step "Click 'Register application'."
step "On the app page, copy the 'Client ID'."
ask GITHUB_OAUTH_CLIENT_ID "Paste the Client ID:"
step "Click 'Generate a new client secret', then copy it immediately (shown once)."
ask_secret GITHUB_OAUTH_CLIENT_SECRET "Paste the Client secret:"
write_env GITHUB_OAUTH_CLIENT_ID "$GITHUB_OAUTH_CLIENT_ID"
write_env GITHUB_OAUTH_CLIENT_SECRET "$GITHUB_OAUTH_CLIENT_SECRET"
say ""
warn "NEXTAUTH_URL in .env must match wherever you load the app in the browser."
note "To test GitHub sign-in through the tunnel, temporarily set:"
note "  NEXTAUTH_URL=${TUNNEL_URL}"
note "and load the dashboard at that URL, not localhost:3000. Switch it back"
note "to http://localhost:3000 for everyday local dev (the review pipeline"
note "itself — webhooks and Installations — doesn't depend on NEXTAUTH_URL)."

# ── Stage 3: webhook secret (generate before creating the App) ────────────
stage "Generate the webhook secret"
say "This is a random string only you and GitHub know. It's how the webhook"
say "handler proves a payload really came from GitHub before doing anything"
say "else (see CLAUDE.md, 'The review pipeline')."
GITHUB_WEBHOOK_SECRET=$(openssl rand -hex 32)
note "Generated: $GITHUB_WEBHOOK_SECRET"
write_env GITHUB_WEBHOOK_SECRET "$GITHUB_WEBHOOK_SECRET"
step "Keep this terminal visible — you'll paste this exact value into GitHub"
step "in the next stage, under 'Webhook secret'."
pause "Got it — continue when ready"

# ── Stage 4: the GitHub App itself ─────────────────────────────────────────
stage "Create the GitHub App (the reviewer bot identity)"
say "This is the app that reads pull requests and posts review comments as"
say "its own bot identity, never as you. Repository access comes only from"
say "here — never from the OAuth app above (docs/adr/0001)."
open_url "https://github.com/settings/apps/new"
step "GitHub App name: anything unique, e.g. 'devme-review-dev'."
step "Homepage URL: ${TUNNEL_URL}"
step "Uncheck 'Active' under Webhook for now — leave it, we'll fill in the URL next."
step "Webhook URL: ${TUNNEL_URL}/api/webhooks/github"
step "Webhook secret: paste the value generated in the previous stage:"
note "  $GITHUB_WEBHOOK_SECRET"
step "Check 'Active' now that URL + secret are filled in."
say ""
say "Under 'Repository permissions', set:"
step "Contents: Read-only"
step "Issues: Read-only"
step "Pull requests: Read and write"
step "Checks: Read and write"
say ""
say "Under 'Subscribe to events', check exactly:"
step "Pull request"
step "Installation"
step "Installation repositories"
say ""
step "Under 'Where can this GitHub App be installed?', choose whichever you"
step "prefer for testing (usually 'Only on this account')."
step "Click 'Create GitHub App'."
say ""
step "On the app's settings page, copy the 'App ID' near the top."
ask GITHUB_APP_ID "Paste the App ID:"
write_env GITHUB_APP_ID "$GITHUB_APP_ID"

# ── Stage 5: private key ───────────────────────────────────────────────────
stage "Download and encode the private key"
say "The App authenticates as itself using a private key, not a password."
step "On the same App settings page, scroll to 'Private keys' and click"
step "'Generate a private key'. A .pem file downloads."
DEFAULT_PEM="$HOME/Downloads"
say ""
say "This wizard needs to read that file to convert it into the single-line,"
say "\\n-escaped form appClient.ts expects (it un-escapes \\n back to real"
say "newlines at startup)."
ask PEM_PATH "Full path to the downloaded .pem file [e.g. ${DEFAULT_PEM}/devme-review-dev.YYYY-MM-DD.private-key.pem]:"
if [[ ! -f "$PEM_PATH" ]]; then
  warn "Can't find '$PEM_PATH'. You can convert it yourself later with:"
  note "  awk 'BEGIN{ORS=\"\\\\n\"} {print}' your-key.pem"
  note "and set GITHUB_APP_PRIVATE_KEY in .env to the output, quoted."
  SKIPPED+=("GITHUB_APP_PRIVATE_KEY: convert $PEM_PATH by hand and add it to .env")
else
  GITHUB_APP_PRIVATE_KEY=$(awk 'BEGIN{ORS="\\n"} {print}' "$PEM_PATH")
  write_env GITHUB_APP_PRIVATE_KEY "\"$GITHUB_APP_PRIVATE_KEY\""
  note "Converted and wrote GITHUB_APP_PRIVATE_KEY. The .pem on disk is no"
  note "longer needed by the app — delete it once you've confirmed .env looks"
  note "right, since it's a live credential sitting in your Downloads folder."
fi

# ── Stage 6: install the App ───────────────────────────────────────────────
stage "Install the App on a test repository"
say "Nothing mints an Installation row until the App is actually installed"
say "somewhere. Pick a throwaway repo (or a real one you don't mind test"
say "pull requests hitting) with at least one open Issue to link against."
open_url "https://github.com/settings/apps"
step "Find the App you just created and click 'Install App' in the left sidebar."
step "Choose an account, then either 'All repositories' or select one test repo."
step "Click 'Install'."
say ""
say "That install fires the 'installation' webhook at your tunnel, which"
say "creates the Installation row this app needs. Confirm it worked:"
step "In another terminal: bun run dev (and separately: bun run worker)"
step "Then check the dev server logs for the installation webhook landing."
confirm "Installed, and you can see it created an Installation? (you can also check later with 'bun run db:seed-key', which lists Installations)"

finish

say "Next: bun run db:seed-key   (adds an Anthropic Provider Key to the Installation)"
say "Then: open a PR on the test repo with 'Closes #<issue-number>' in its body."
